const Author = require("../module/author")

const topAuthors = [
  "William Shakespeare",
  "Charles Dickens",
  "J.K. Rowling",
  "George Orwell",
  "Ernest Hemingway",
  "Mark Twain",
  "F. Scott Fitzgerald",
  "Virginia Woolf",
  "Leo Tolstoy",
  "Jane Austen",
  "Emily Dickinson",
  "Gabriel Garcia Marquez",
  "John Steinbeck",
  "James Joyce",
  "Haruki Murakami",
  "Edgar Allan Poe",
  "Stephen King",
  "Oscar Wilde",
  "J.R.R. Tolkien",
  "Agatha Christie",
  "George R.R. Martin",
  "Thomas Hardy",
  "Arthur Conan Doyle",
  "William Faulkner",
  "H.P. Lovecraft",
  "E. M. Forster",
  "Herman Melville",
  "T.S. Eliot",
  "Harper Lee",
  "Fyodor Dostoevsky",
  "Miguel de Cervantes",
  "Franz Kafka",
  "Henry James",
  "Dante Alighieri",
  "Kurt Vonnegut",
  "Virginia Woolf",
  "Philip K. Dick",
  "Joseph Conrad",
  "Lewis Carroll",
  "Graham Greene",
  "Aldous Huxley",
  "J.D. Salinger",
  "H.G. Wells",
  "Margaret Atwood",
  "Neil Gaiman",
  "Toni Morrison",
  "Jack Kerouac",
  "Sylvia Plath",
  "Langston Hughes",
  "Eudora Welty",
  "John Updike",
  "Ursula K. Le Guin",
  "Ralph Ellison",
  "Zora Neale Hurston",
  "Albert Camus",
  "Roald Dahl",
  "Salman Rushdie",
  "Samuel Beckett",
  "Arthur Miller",
  "Flannery O'Connor",
  "Truman Capote",
  "Tennessee Williams",
  "Ray Bradbury",
  "Ian McEwan",
  "Kazuo Ishiguro",
  "Thomas Pynchon",
  "Cormac McCarthy",
  "Philip Roth",
  "Doris Lessing",
  "Milan Kundera",
  "Orhan Pamuk",
  "Paulo Coelho",
  "Mario Vargas Llosa",
  "Gabriel Garcia Marquez",
  "Mo Yan",
  "Harold Pinter",
  "John Fowles",
  "Don DeLillo",
  "John Le Carré",
  "J.M. Coetzee",
  "Naguib Mahfouz",
  "William Golding",
  "Gunther Grass",
  "Octavio Paz",
  "Derek Walcott",
  "Seamus Heaney",
  "Wislawa Szymborska",
  "V.S. Naipaul",
  "Jose Saramago",
  "Nadine Gordimer",
  "Elfriede Jelinek",
  "Ken Kesey",
  "Patrick White",
  "Eugene Ionesco",
  "Harold Pinter",
  "Tom Stoppard",
  "Vladimir Nabokov",
  "Günter Grass",
  "Carlos Fuentes",
  "Isabel Allende",
  "Jorge Luis Borges",
  "Pablo Neruda",
  "Octavio Paz",
  "Mario Vargas Llosa",
  "Julio Cortázar",
  "Gabriela Mistral",
  "Isaac Asimov",
  "Arthur C. Clarke",
  "Ray Bradbury",
]

const main = async () => {
  for (let name of topAuthors) {
    try {
      await Author.spawnByName(name)
      console.log(`${name} added.`)
    } catch (e) {
      console.log(`${name} failed.`, e)
    }
  }
}

main()
