const Author = require("../module/author")

const topAuthors = [
  "William Shakespeare",
  "Jane Austen",
  "Charles Dickens",
  "Mark Twain",
  "Fyodor Dostoevsky",
  "Leo Tolstoy",
  "J.R.R. Tolkien",
  "George Orwell",
  "Emily Dickinson",
  "Herman Melville",
  "Ernest Hemingway",
  "Virginia Woolf",
  "Toni Morrison",
  "Harper Lee",
  "F. Scott Fitzgerald",
  "Arthur Conan Doyle",
  "Oscar Wilde",
  "George R.R. Martin",
  "J.D. Salinger",
  "Gabriel Garcia Marquez",
  "John Steinbeck",
  "H.P. Lovecraft",
  "Ralph Waldo Emerson",
  "Nathaniel Hawthorne",
  "Stephen King",
  "Agatha Christie",
  "Walt Whitman",
  "Charlotte Bronte",
  "Louisa May Alcott",
  "Rudyard Kipling",
  "Edgar Allan Poe",
  "John Green",
  "Jane Goodall",
  "Roald Dahl",
  "Kurt Vonnegut",
  "James Joyce",
  "Maya Angelou",
  "J.K. Rowling",
  "John Milton",
  "William Faulkner",
  "Miguel de Cervantes",
  "Chinua Achebe",
  "Pablo Neruda",
  "Jack Kerouac",
  "W. Somerset Maugham",
  "Franz Kafka",
  "Sylvia Plath",
  "C.S. Lewis",
  "H.G. Wells",
  "T.S. Eliot",
  "Edith Wharton",
  "Thomas Hardy",
  "Vladimir Nabokov",
  "Albert Camus",
  "Aldous Huxley",
  "Henry David Thoreau",
  "Ayn Rand",
  "E.E. Cummings",
  "Anton Chekhov",
  "Margaret Atwood",
  "William Wordsworth",
  "Rabindranath Tagore",
  "John Keats",
  "Jonathan Swift",
  "Homer",
  "Jules Verne",
  "Samuel Beckett",
  "W.B. Yeats",
  "Robert Frost",
  "Hans Christian Andersen",
  "Voltaire",
  "Virginia Satir",
  "Rumi",
  "O. Henry",
  "Jorge Luis Borges",
  "Joseph Conrad",
  "E.B. White",
  "Lewis Carroll",
  "Tennessee Williams",
  "Isaac Asimov",
  "Aristotle",
  "Dante Alighieri",
  "Neil Gaiman",
  "Marianne Williamson",
  "Rainer Maria Rilke",
  "Plato",
  "Gustave Flaubert",
  "Hermann Hesse",
  "Johann Wolfgang von Goethe",
  "Oscar Hijuelos",
  "Kazuo Ishiguro",
  "W. H. Auden",
  "Naguib Mahfouz",
  "Octavia Butler",
  "Paulo Coelho",
  "Aldo Leopold",
  "Helen Keller",
  "Ernest J. Gaines",
  "Milan Kundera",
  "Rudolf Steiner",
  "Italo Calvino",
  "Albert Einstein",
]

const main = async () => {
  for (let name of topAuthors) {
    try {
      await Author.spawnByName(name)
      console.log(`${name} added.`)
    } catch (e) {
      console.log(`${name} failed.`, e)
    }
  }
}

main()
